name: padisahlar_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.3
  share: ^2.0.1
  get: ^4.1.4
  fluttertoast: ^8.0.3
  loading_alert_dialog: ^1.0.0+2
  lottie: ^1.0.1
  carousel_slider: ^1.3.0
  carousel_pro: ^1.0.0
  flutter_speed_dial: ^3.0.5
  assets_audio_player: ^3.0.3+3
  facebook_audience_network: ^0.9.0
  audioplayers: ^0.18.3
  provider: ^5.0.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/Icons/icon_home.png
    - assets/Icons/icon_settings.png
    - assets/Icons/icon_mushrooms.png
    - assets/Icons/icon_info.png
    - assets/settings/share.png
    - assets/settings/settings.png
    - assets/settings/settings.gif
    - assets/settings/osmanli.png 
    - assets/settings/turkey.png 
    - assets/settings/english.png 
    - assets/settings/facebook.png
    - assets/settings/instagram.png
    - assets/settings/twitter.png
    - assets/settings/whatsapp.png 
    - assets/settings/google_play.png 
    - assets/settings/gmail.png 
    - assets/settings/github.png 
    - assets/loading.json
    - assets/back.json
    - assets/next.json
    - assets/padisahlar/p1.png
    - assets/padisahlar/p2.png
    - assets/padisahlar/p3.png
    - assets/padisahlar/p4.png
    - assets/padisahlar/p5.png
    - assets/padisahlar/p6.png
    - assets/padisahlar/p7.png
    - assets/padisahlar/p8.png
    - assets/padisahlar/p9.png
    - assets/padisahlar/p10.png
    - assets/padisahlar/p11.png
    - assets/padisahlar/p12.png
    - assets/padisahlar/p13.png
    - assets/padisahlar/p14.png
    - assets/padisahlar/p15.png
    - assets/padisahlar/p16.png
    - assets/padisahlar/p17.png
    - assets/padisahlar/p18.png
    - assets/padisahlar/p19.png
    - assets/padisahlar/p20.png
    - assets/padisahlar/p21.png
    - assets/padisahlar/p22.png
    - assets/padisahlar/p23.png
    - assets/padisahlar/p24.png
    - assets/padisahlar/p25.png
    - assets/padisahlar/p26.png
    - assets/padisahlar/p27.png
    - assets/padisahlar/p28.png
    - assets/padisahlar/p29.png
    - assets/padisahlar/p30.png
    - assets/padisahlar/p31.png
    - assets/padisahlar/p32.png
    - assets/padisahlar/p33.png
    - assets/padisahlar/p34.png
    - assets/padisahlar/p35.png
    - assets/padisahlar/p36.png
    - assets/mushrooms.png
    - assets/yildiz.png
    - assets/tgr.png
    - assets/mushrooms_list1.png
    - assets/mushrooms_list2.png
    - assets/mushrooms_list3.png
    - assets/galeri/1.jpg
    - assets/galeri/2.jpeg
    - assets/galeri/3.jpeg
    - assets/galeri/4.jpeg
    - assets/galeri/5.jpg
    - assets/galeri/6.jpg
    - assets/galeri/7.jpg
    - assets/galeri/8.jpeg
    - assets/galeri/9.jpg
    - assets/galeri/10.jpg
    - assets/galeri/11.jpg
    - assets/galeri/12.jpg
    - assets/galeri/13.jpg
    - assets/galeri/14.jpg
    - assets/galeri/15.jpg
    - assets/galeri/16.jpg
    - assets/galeri/17.jpg
    - assets/galeri/18.jpg
    - assets/galeri/19.jpg
    - assets/galeri/20.jpg
    - assets/galeri/21.jpg
    - assets/galeri/22.jpg
    - assets/galeri/23.jpg
    - assets/galeri/24.jpg
    - assets/galeri/25.jpg
    - assets/galeri/26.jpg
    - assets/galeri/27.jpg
    - assets/galeri/28.jpg
    - assets/galeri/29.jpg
    - assets/galeri/30.jpg
    - assets/galeri/31.jpg
    - assets/galeri/32.jpg
    - assets/galeri/33.jpg
    - assets/galeri/34.jpg
    - assets/galeri/35.jpg
    - assets/galeri/36.jpg
    - assets/galeri/37.jpg
    - assets/galeri/38.jpg
    - assets/galeri/39.jpg
    - assets/galeri/40.png
    - assets/galeri/41.jpg
    - assets/galeri/42.jpg
    - assets/galeri/43.jpg
    - assets/galeri/44.jpg
    - assets/music.mp3


    
 
  fonts:
    - family: Comfortaa
      fonts:
      - asset: assets/fonts/Comfortaa-VariableFont_wght.ttf
      - asset: assets/fonts/Comfortaa-Regular.ttf
        weight: 400
      - asset: assets/fonts/Comfortaa-Medium.ttf
        weight: 500
      - asset: assets/fonts/Comfortaa-Bold.ttf
        weight: 700
      - asset: assets/fonts/Comfortaa-Light.ttf
        weight: 300
      - asset: assets/fonts/Comfortaa-SemiBold.ttf
        weight: 600  


  uses-material-design: true

